### PR TITLE
Update imageMapResizer.js

### PR DESCRIPTION
**Pull request by Sioweb**
I've added some reset. So every time you call the plugin it will reset it self. You can use it in fullscreen mode now. Added some detacheEvents and coords-reset in line 99 - 109.

Thank u for this great plugin.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Have a look at the dev branch, it has a much simpler solution to recalling the function. It basically leaves a marker on setup and the next time if it see it, then setup is skipped and just the resize function is called.

**Comment by davidjbradshaw** [comment]
What was the issue with fullscreen? Do we need to add a listener for `fullscreenchange`?

https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange

**Comment by Sioweb** [comment]
Thanks.

My problem was, that the script change the coords attribute onresize, so the MAP-Element was wrong in fullscreen. It doesn't fire an resize or something on fullscreen so it would be good to add the fullscreen event.

**Comment by davidjbradshaw** [comment]
Oh then we could just add an event listener to detect the fullscreenchange event. 

https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange

**Pull request closed without merging**
